# insere dados na tabela funcionarios;
use ADS2_curso;
insert funcionarios (id, nome, salario, departamento) values (1,'Fernando', 1600, 'TI');
insert funcionarios (id, nome, salario, departamento) values (null, 'Guilherme', 2500, 'Juridico');
insert funcionarios (id, nome, salario, departamento) values (null, 'Fabio', 1700, 'TI');
insert funcionarios (id, nome, salario, departamento) values (null, 'Jose', 1800, 'Marketing');
insert funcionarios (id, nome, salario, departamento) values (null, 'Isabela', 5200, 'Juridico');
insert funcionarios (id, nome, salario, departamento) values (null, 'Marta', 3400, 'TI');
insert funcionarios (id, nome, salario, departamento) values (null, 'Cristina', 2550, 'Juridico');
insert funcionarios (id, nome, salario, departamento) values (null, 'Talita', 2700, 'TI');
insert funcionarios (id, nome, salario, departamento) values (null, 'Jorge', 1450, 'Marketing');
insert funcionarios (id, nome, salario, departamento) values (null, 'Albertina', 5200, 'Juridico');
insert funcionarios (id, nome, salario, departamento) values (null, 'Maria', 3000, 'RH'); 